# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EC2qcp0aoctOiWucaB8LqXBeG93uT9Tw
"""

import streamlit as st

try:
    import pandas as pd
    import mechanicalsoup
    import re
    import time
    import io
except ImportError as e:
    st.error(f"❌ Missing library: {e}")
    st.info("Please check your requirements.txt includes all dependencies.")
    st.stop()

# --- Page Config ---
st.set_page_config(
    page_title="SEEK Job Scraper",
    page_icon="🔍",
    layout="centered"
)

# --- App Title ---
st.title("🔍 SEEK Job Scraper")
st.write("Scrapes current job listings from SEEK for **Rotorua & Central Bay of Plenty** (25km radius).")
st.divider()

# --- Configuration ---
INITIAL_URL = "https://nz.seek.com/jobs/in-Rotorua-Central-Bay-of-Plenty?distance=25"
REQUEST_DELAY_SECONDS = 4


# --- Helper: Extract Job Details from a Single Card ---
def extract_job_details_from_card(card, browser):
    job_title = 'N/A'
    job_url = 'N/A'
    company_name = 'N/A'
    location = 'N/A'
    job_category = 'N/A'

    # Job Title and URL
    job_title_tag = card.find('a', {'data-automation': 'jobTitle'})
    if job_title_tag and job_title_tag.get_text(strip=True):
        job_title = job_title_tag.get_text(strip=True)
        job_url = browser.absolute_url(job_title_tag['href'])
    else:
        return None

    # Company Name
    company_name_tag = card.find('span', {'data-automation': 'jobCompany'}) or \
                       card.find('a', {'data-automation': 'jobCompany'})
    if company_name_tag:
        company_name = company_name_tag.get_text(strip=True)
    elif 'aria-label' in card.attrs and '-' in card['aria-label']:
        fallback = card['aria-label'].split('-', 1)[0].replace('job card', '').strip()
        if fallback:
            company_name = fallback

    # Location
    location_element = card.find(attrs={'data-automation': 'job-detail-location'}) or \
                       card.find('span', {'data-automation': 'jobLocation'})
    if location_element:
        location_link = location_element.find('a')
        location = location_link.get_text(strip=True) if location_link else location_element.get_text(strip=True)

    # Category
    category_element = card.find(attrs={'data-automation': 'job-detail-classification'}) or \
                       card.find('span', {'data-automation': 'jobClassification'})
    if category_element:
        category_link = category_element.find('a')
        job_category = category_link.get_text(strip=True) if category_link else category_element.get_text(strip=True)

    return {
        'Company Name': company_name,
        'Job Title': job_title,
        'Job Category': job_category,
        'Location': location,
        'Link to Ad': job_url
    }


# --- Helper: Find Next Page Link ---
def find_next_page_link(page):
    next_page_link = page.find('a', {'data-automation': 'page-next'})
    if not next_page_link:
        next_page_link = page.find('a', {'rel': 'next'})
    if not next_page_link:
        next_page_link = page.find('a', string=re.compile(r'Next|>', re.IGNORECASE))
    return next_page_link


# --- Main Scraper ---
def run_scraper(status_box, progress_bar):
    browser = mechanicalsoup.StatefulBrowser()
    all_jobs_data = []
    page_number = 1
    current_url = INITIAL_URL

    while True:
        status_box.info(f"⏳ Scraping page {page_number}...")

        try:
            browser.open(current_url)
            page = browser.get_current_page()
        except Exception as e:
            status_box.error(f"❌ Could not load page {page_number}: {e}")
            break

        job_cards = page.find_all('article', {'data-testid': 'job-card'})

        if not job_cards:
            status_box.warning(f"No job cards found on page {page_number}. Stopping.")
            break

        for card in job_cards:
            job_details = extract_job_details_from_card(card, browser)
            if job_details:
                all_jobs_data.append(job_details)

        progress_bar.progress(min(page_number * 10, 100))  # rough progress indicator

        next_page_link = find_next_page_link(page)
        if not next_page_link or not next_page_link.get('href'):
            break

        current_url = browser.absolute_url(next_page_link['href'])
        page_number += 1
        time.sleep(REQUEST_DELAY_SECONDS)

    return pd.DataFrame(all_jobs_data)

category_summary = jobs_df['Job Category'].value_counts().reset_index()
category_summary.columns = ['Job Category', 'Number of Jobs']


# --- Convert DataFrame to Excel in memory ---
def convert_to_excel(df):
    output = io.BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        # Write the category summary DataFrame to the second sheet
        category_summary.to_excel(writer, sheet_name='Category Summary', index=False)
        df.to_excel(writer, index=False, sheet_name='Job Listings')
    return output.getvalue()


# --- Run Button ---
if st.button("▶️  Start Scraping", type="primary", use_container_width=True):

    status_box = st.empty()
    progress_bar = st.progress(0)

    jobs_df = run_scraper(status_box, progress_bar)

    progress_bar.progress(100)

    if jobs_df.empty:
        status_box.error("❌ No jobs were collected. The site structure may have changed.")
    else:
        status_box.success(f"✅ Done! Found **{len(jobs_df)} jobs** across all pages.")

        st.divider()

        # Summary
        st.subheader("📊 Results Summary")
        col1, col2, col3 = st.columns(3)
        col1.metric("Total Jobs", len(jobs_df))
        col2.metric("Companies", jobs_df['Company Name'].nunique())
        col3.metric("Categories", jobs_df['Job Category'].nunique())

        # Table Preview
        st.subheader("📋 Job Listings Preview")
        st.dataframe(jobs_df, use_container_width=True)

        st.divider()

        # Download Excel
        excel_data = convert_to_excel(jobs_df)
        st.download_button(
            label="📥 Download as Excel (.xlsx)",
            data=excel_data,
            file_name="Rotorua_Job_Listings.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            use_container_width=True,
            type="primary"
        )

st.divider()
st.caption("Built with Streamlit · Data sourced from SEEK NZ · Please use responsibly.")